CREATE TABLE  "DISTRITO" 
   (	"DISTRITO" NUMBER(3,0), 
		"NOMBRE" VARCHAR2(50), 
		PRIMARY KEY ("DISTRITO") ENABLE
   )
/
CREATE SEQUENCE SEQ_DISTRITO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/


CREATE TABLE  "TIPO_PRODUCTO" 
   (	"TIPO_PRODUCTO" NUMBER(3,0), 
		"NOMBRE" VARCHAR2(50), 
		PRIMARY KEY ("TIPO_PRODUCTO") ENABLE
   )
/
CREATE SEQUENCE SEQ_TIPO_PRODUCTO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE  "CLIENTE"
   (	"CLIENTE" NUMBER(3,0), 
		"NOMBRE" VARCHAR2(50), 
		"NUMERO_DOCUMENTO" VARCHAR2(50), 
		"TIPO_DOCUMENTO" VARCHAR2(3), 
		PRIMARY KEY ("CLIENTE") ENABLE
   )
/
CREATE SEQUENCE SEQ_CLIENTE MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/


CREATE TABLE  "PRODUCTO" 
   (	"PRODUCTO" NUMBER(3,0), 
		"NOMBRE" VARCHAR2(50), 
		"PRECIO" NUMBER(19,2),
	    "TIPO_PRODUCTO" NUMBER(3,0), 		
		PRIMARY KEY ("PRODUCTO") ENABLE,
		CONSTRAINT "PRODUCTO_TIPO_PRODUCTO_FK" FOREIGN KEY ("TIPO_PRODUCTO")  REFERENCES  "TIPO_PRODUCTO" ("TIPO_PRODUCTO") ENABLE
   )
/
CREATE SEQUENCE SEQ_PRODUCTO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/
   
   
CREATE TABLE  "TIENDA" 
   (	"TIENDA" NUMBER(2,0), 
		"NOMBRE" VARCHAR2(50), 
		"DISTRITO" NUMBER(3,0), 
		PRIMARY KEY ("TIENDA") ENABLE,
		CONSTRAINT "TIENDA_DISTRITO_FK" FOREIGN KEY ("DISTRITO")  REFERENCES  "DISTRITO" ("DISTRITO") ENABLE
   )
/
CREATE SEQUENCE SEQ_TIENDA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/


CREATE TABLE  "VENTA" 
   (	
    "VENTA" NUMBER(10,0), 
	"CLIENTE" NUMBER(3,0), 
	"PRODUCTO" NUMBER(3,0), 
	"TIENDA" NUMBER(2,0), 
	"PRECIO" NUMBER(19,2), 
	"FECHA" DATE, 
	"CANTIDAD" NUMBER(2,0), 
	"MONEDA" VARCHAR2(5),
	"PROCESADO" VARCHAR2(1) DEFAULT 'N', 
	 CONSTRAINT "VENTA_PK" PRIMARY KEY ("VENTA") ENABLE, 
	 CONSTRAINT "VENTA_CLIENTE_FK" FOREIGN KEY ("CLIENTE")
	  REFERENCES  "CLIENTE" ("CLIENTE") ENABLE, 
	 CONSTRAINT "VENTA_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO")
	  REFERENCES  "PRODUCTO" ("PRODUCTO") ENABLE, 
	 CONSTRAINT "VENTA_TIENDA_FK" FOREIGN KEY ("TIENDA")
	  REFERENCES  "TIENDA" ("TIENDA") ENABLE
   )
/

CREATE SEQUENCE   "SEQ_VENTA"  MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/


CREATE INDEX  "VENTA_IDX1" ON  "VENTA" ("PROCESADO", "TIENDA")
/

CREATE OR REPLACE TRIGGER  "BI_VENTA" 
  before insert on "VENTA"               
  for each row  
	begin   
		select "SEQ_VENTA".nextval into :NEW.VENTA from dual; 
	end; 

/
ALTER TRIGGER  "BI_VENTA" ENABLE
/

CREATE TABLE  "FECHA" 
   (	"FECHA" NUMBER(7,0), 
		"AÑO" NUMBER(4,0), 
		"MES" NUMBER(2,0), 
		"DIA" NUMBER(2,0), 
		"HORA" NUMBER(2,0), 
		PRIMARY KEY ("FECHA") ENABLE
   )
/
CREATE SEQUENCE SEQ_FECHA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TABLE  "TOTAL_DISTRITO" 
   (	
    "DISTRITO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(50), 
	"TOTAL" NUMBER(19,2), 
	 CONSTRAINT "TOTAL_DISTRITO_PK" PRIMARY KEY ("DISTRITO") ENABLE
   )
/
CREATE INDEX  "TOTAL_DISTRITO_IDX1" ON  "TOTAL_DISTRITO" ("NOMBRE")
/


   
CREATE TABLE  "TOTAL_CLIENTE" 
   (	
    "CLIENTE" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(50), 
	"TOTAL" NUMBER(19,2), 
	 CONSTRAINT "TOTAL_CLIENTE_PK" PRIMARY KEY ("CLIENTE") ENABLE
   )
/
CREATE INDEX  "TOTAL_CLIENTE_IDX1" ON  "TOTAL_CLIENTE" ("NOMBRE")
/


CREATE TABLE  "TOTAL_PRODUCTO" 
   (	
    "PRODUCTO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(50), 
	"TOTAL" NUMBER(19,2), 
	"CANTIDAD" NUMBER(19,0), 
	 CONSTRAINT "TOTAL_PRODUCTO_PK" PRIMARY KEY ("PRODUCTO") ENABLE
   )
/
CREATE INDEX  "TOTAL_PRODUCTO_IDX1" ON  "TOTAL_PRODUCTO" ("NOMBRE")
/


CREATE TABLE  "TOTAL_TIENDA" 
   (	
    "TIENDA" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(50), 
	"TOTAL" NUMBER(19,2), 
	 CONSTRAINT "TOTAL_TIENDA_PK" PRIMARY KEY ("TIENDA") ENABLE
   )
/

CREATE INDEX  "TOTAL_TIENDA_IDX1" ON  "TOTAL_TIENDA" ("NOMBRE")
/

CREATE TABLE  "TOTAL_VENTA" 
   (	
    "TIENDA" NUMBER(2,0), 
	"CLIENTE" NUMBER(3,0), 
	"PRODUCTO" NUMBER(3,0), 
	"FECHA" NUMBER(7,0), 
	"TIPO_PRODUCTO" NUMBER(3,0), 
	"DISTRITO" NUMBER(3,0), 
	"NOMBRE_TIENDA" VARCHAR2(50), 
	"NOMBRE_CLIENTE" VARCHAR2(50), 
	"NOMBRE_PRODUCTO" VARCHAR2(50), 
	"TOTAL_SOLES" NUMBER(19,2),
	"TOTAL_DOLARES" NUMBER(19,2),
	"CANTIDAD" NUMBER(10,0), 
	 CONSTRAINT "TOTAL_VENTA_PK" PRIMARY KEY ("TIENDA", "CLIENTE", "PRODUCTO", "FECHA", "TIPO_PRODUCTO", "DISTRITO") ENABLE, 
	 CONSTRAINT "TOTAL_VENTA_TIENDA_FK" FOREIGN KEY ("TIENDA") REFERENCES  "TIENDA" ("TIENDA") ENABLE, 
	 CONSTRAINT "TOTAL_VENTA_CLIENTE_FK" FOREIGN KEY ("CLIENTE") REFERENCES  "CLIENTE" ("CLIENTE") ENABLE, 
	 CONSTRAINT "TOTAL_VENTA_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO") REFERENCES  "PRODUCTO" ("PRODUCTO") ENABLE,
	 CONSTRAINT "TOTAL_VENTA_FECHA_FK" FOREIGN KEY ("FECHA") REFERENCES  "FECHA" ("FECHA") ENABLE,	 
	 CONSTRAINT "TOTAL_VENTA_TIPO_PRODUCTO_FK" FOREIGN KEY ("TIPO_PRODUCTO") REFERENCES  "TIPO_PRODUCTO" ("TIPO_PRODUCTO") ENABLE,
	 CONSTRAINT "TOTAL_VENTA_DISTRITO_FK" FOREIGN KEY ("DISTRITO") REFERENCES  "DISTRITO" ("DISTRITO") ENABLE
   )
/

CREATE INDEX  "TOTAL_VENTA_IDX1" ON  "TOTAL_VENTA" ("FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX10" ON  "TOTAL_VENTA" ("NOMBRE_TIENDA", "NOMBRE_CLIENTE", "NOMBRE_PRODUCTO", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX11" ON  "TOTAL_VENTA" ("NOMBRE_TIENDA", "NOMBRE_PRODUCTO", "NOMBRE_CLIENTE", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX12" ON  "TOTAL_VENTA" ("NOMBRE_CLIENTE", "NOMBRE_TIENDA", "NOMBRE_PRODUCTO", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX13" ON  "TOTAL_VENTA" ("NOMBRE_CLIENTE", "NOMBRE_PRODUCTO", "NOMBRE_TIENDA", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX14" ON  "TOTAL_VENTA" ("NOMBRE_PRODUCTO", "NOMBRE_TIENDA", "NOMBRE_CLIENTE", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX15" ON  "TOTAL_VENTA" ("NOMBRE_PRODUCTO", "NOMBRE_CLIENTE", "NOMBRE_TIENDA", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX2" ON  "TOTAL_VENTA" ("CLIENTE", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX3" ON  "TOTAL_VENTA" ("TIENDA", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX4" ON  "TOTAL_VENTA" ("PRODUCTO", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX5" ON  "TOTAL_VENTA" ("CLIENTE", "TIENDA", "PRODUCTO", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX6" ON  "TOTAL_VENTA" ("TIENDA", "PRODUCTO", "CLIENTE", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX7" ON  "TOTAL_VENTA" ("CLIENTE", "PRODUCTO", "TIENDA", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX8" ON  "TOTAL_VENTA" ("PRODUCTO", "TIENDA", "CLIENTE", "FECHA")
/

CREATE INDEX  "TOTAL_VENTA_IDX9" ON  "TOTAL_VENTA" ("PRODUCTO", "CLIENTE", "TIENDA", "FECHA")
/


--@E:\JT-Documentos\Maestria\BigData\Supermercado\script_crear_tablas_supermercado.sql
--@C:\Users\RicharFV\script_crear_tablas_supermercado.sql